config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bikes do
    member do
      get 'manage'
    end
    resources :reservations, only: [:create]
  end

  resources :reservations, only: [:show]
  resources :users, only: [:show]
  root to: 'bikes#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  CATEGORIES = %w[VTT Enfant Tandem Vintage]

  mount_uploader :photo, PhotoUploader

  belongs_to :user

  validates :title, presence: true, allow_blank: false
  validates :description, presence: true, allow_blank: false
  validates :category, presence: true, allow_blank: false, inclusion: { in: CATEGORIES }
  validates :price, presence: true, allow_blank: false
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :bike
  belongs_to :user

  validates :date, presence: true
  validates_uniqueness_of :date, scope: :bike_id
end

app/models/user.rb
class User < ApplicationRecord
  LOCALISATION = %w[Paris Lyon Marseille]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :owned_bikes, class_name: 'Bike', foreign_key: :user_id, dependent: :destroy
  has_many :reservations
  has_many :bikes, through: :reservations, class_name: 'Bike', foreign_key: :owner_id

  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :email, uniqueness: true, presence: true, allow_blank: false
  validates :localisation, presence: true, allow_blank: false, inclusion: { in: LOCALISATION }

  geocoded_by :localisation
  after_validation :geocode, if: :will_save_change_to_localisation?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :localisation])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :search, :show]
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  def search
  end

  def index
    @bikes = BikeSearch.new(params).search
    @markers = @bikes.map do |bike|
      {
        lat: bike.user.latitude,
        lng: bike.user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bike: bike })

      }

    end
  end

  def show
    @bike = Bike.find(params[:id])
    # modifs pour display le formulaire de reservation dans le show d'un bike
    @reservation = Reservation.new
  end

  def manage
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    if @bike.save
      redirect_to manage_bike_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @bike.update(bike_params)

    redirect_to manage_bike_path
  end

  def destroy
    @user = @bike.user
    @bike.destroy

    redirect_to user_path(@user)
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    params.require(bike).permit(:title, :description, :category, :motor, :price, :localisation, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def show
    @reservation = current_user.reservations.where(id: params[:id]).first
    if @reservation.nil?
      redirect_to root_path, alert: 'It is not your resa buddy!'
    else
      render :show
    end
  end

  def create
    @bike = Bike.find(params[:bike_id])
    @new_reservation = Reservation.new(reservation_params)
    @new_reservation.bike = @bike
    @new_reservation.user = current_user
    if @new_reservation.save
      redirect_to reservation_path(@new_reservation), alert: 'Reservation was successfully booked!'
    else
      redirect_to bike_path(@bike), alert: 'This bike is not open for reservation at this date!'
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h2><%= bike.user.name %></h2>
<p><%= bike.user.localisation %></p>

app/views/bikes/edit.html.erb
<h1>Bikes#edit</h1>
<p>Find me in app/views/bikes/edit.html.erb</p>

app/views/bikes/index.html.erb
 <div class="main-container">


    <div class="cards">



        <% @bikes.each do |bike| %>
        <div class="card-bike">
          <%= cl_image_tag bike.photo, height: 300, width: 400 %>
          <div class="card-bike-infos">
            <div>
              <h2><%= "#{bike.title}" %></h2>
               <p><%= "#{bike.description}" %></p>
            </div>
            <h2 class="card-bike-pricing"><%= "#{bike.price}" %>€</h2>
            <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-bike-user avatar-bordered" /> -->

          </div>

          <center><%=link_to "Voir le Produit", bike_path(bike), class: 'btn btn-lg btn-warning mx-5'%></center>
          <br>
        </div>

        <% end %>



    </div>


<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>



  </div>

app/views/bikes/manage.html.erb
<h1>Bikes#manage</h1>
<p>Find me in app/views/bikes/manage.html.erb</p>

app/views/bikes/new.html.erb
<h1>Bikes#new</h1>
<p>Find me in app/views/bikes/new.html.erb</p>

app/views/bikes/search.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80);">
  <div class="container">
    <h1><strong> Easy</strong> Ride, <strong>Everywhere.</strong></h1>
    <p>Your ride for the day</p>

    <%= form_with(url: bikes_path, local: true, method: :get) do |form| %>
      <%= select_tag(:category, options_for_select(Bike::CATEGORIES)) %>
      <%= select_tag(:localisation, options_for_select(User::LOCALISATION)) %>
      <%= form.text_field :price, placeholder: 'Maximum price' %>
      <%= date_field(:reservation, :start_date, class: 'flatpickr') %>
      <br>
      <span class="checkbox">
        <input type="checkbox" id="checkbox_1" name="motor">
        <label for="checkbox_1"><i class="fas fa-cog"></i>Motorised ?</label>
      </span>
      <br><br>
      <%= form.submit 'Bike', class: 'btn btn-flat' %>

    <% end %>

  </div>
</div>

app/views/bikes/show.html.erb
<div id="fullscreen_bg" class="fullscreen_bg" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1481106839235-a2c71e2564de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60);">
  <div class="card-bike-show" >
    <div>
      <%= cl_image_tag @bike.photo, height: 300, width: 500 %>
    </div>

  <div>
    <br>
    <h2><%= "#{@bike.title}" %></h2>
    <p>Disponible à : <strong><%= "#{@bike.user.localisation}" %></strong></p>
    <p><%= "#{@bike.description}" %></p>
    <br>
    <h4 class="alert alert-secondary" role="alert"><strong>TOTAL :</strong> <%= "#{@bike.price}" %>€</h4>
    <p><light>dont <strong>4€</strong> de frais de service </light></p>
  </div>

  <%= simple_form_for [@bike, @reservation] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.date_select :date, as: :date, class: 'flatpickr' %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-lg btn-warning' %>
  </div>
<% end %>

</div>
</div>






<!-- app/views/articles/show.html.erb -->



<!-- simple_form [@bike, @reservation] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= body_class %>">
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/show.html.erb
<!-- <h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

Ceci est un test
 -->


<h1><center> <strong>Merci pour votre reservation!</strong></center></h1>



<center><iframe src="https://giphy.com/embed/Oe2Tw5GnKRQwo" width="480" height="335" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/interesting-evolution-bicycle-Oe2Tw5GnKRQwo">via GIPHY</a></p></center><

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><%= notice %></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><%= alert %></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
    This site is made with <i class="fas fa-heart"></i> by Bike Me!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "/", class: "navbar-brand" do %>
       <div class="navbar-logo">Bike Me</div>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Profil", "/users/1", class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>

app/views/shared/navbar/_search.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://i.pinimg.com/originals/b5/d2/f4/b5d2f4b06c0390c4dadb66da03ade490.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
          <%= link_to "Faire louer son Vélo", "#", class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Trouver un Vélo", "#", class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Inscription", "#", class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Connexion", "#", class: "nav-link" %>
        </li>
<!--
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li> -->
      </ul>
    </div>
  </div>

app/views/users/profil.html.erb
<h1>Users#profil</h1>
<p>Find me in app/views/users/profil.html.erb</p>

app/views/users/show.html.erb
<div id="fullscreen_bg" class="fullscreen_bg">
  <div class="profil-card" >
    <div class="profil-card-img">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyPSwvdIdV2OVVBr0j8il7gFw4wZsqt0hujhxbvptNi2Ryi8YfyQ" alt="">
    </div>

    <div class="name">
      <h1><%= @user.name%></h1>
    </div>

    <div class="adresse">
      <p><%= @user.email%></p>
    </div>

    <div class="card-profil">

      <div class="historique">
          <h2>Historique des réservations:</h2>
          <div class="card-product-infos">
            <!-- <div></div> -->
            <% @user.reservations.each do |reservation|%>
            <p><strong><%= reservation.bike.title %></strong></p>
            <p><%= reservation.bike.description%></p>
            <p><strong><%= reservation.bike.price%></strong></p>
            <%end%>
          </div>
      </div>
    </div>
  </div>

</div>